### ISSUE TITLE
Public artifact?

### ISSUE THREAD

**Issue by BFergerson** [extenda/vertx-redis-clustermanager#7]
Is this project listed in any public repositories? I cannot find it and the repository it appears to be listed in (https://repo.extendaretail.com/repository/maven-releases) requires username/password.

**Comment by dominik-cnx** [comment]
Also see 
https://github.com/extenda/vertx-redis-clustermanager/pull/102

Our team is currently testing this cluster manager with vert.x 4.5.1 on a k8s cluster on AWS. We use the Redis compatible Amazon MemoryDB (https://aws.amazon.com/memorydb/) and so far it looks promising.

However, we would also require an official artifact, ideally on Maven Central to go forward with the deployment. We are happy to help setting up a GitHub Actions based build that then deploys to Maven Central. 

Let me know your thoughts, thx.

**Comment by sasjo** [comment]
I'm looking into this. The project is stable and we're ready to release it publicly. We'd need to make the following changes

1. Change packages to com.retailsvc
2. Make sure we're compliant with latest Vert.x
3. Release 1.0.0
